# Site settings
baseurl = "https://mattallan.me"
themesDir = "./themes"
languageCode = "en-us"
title = "Matt Allan"
theme = "brutal"
pygmentsCodeFences=true
pygmentsUseClasses=true
paginate = 5

[params]
  description = "Articles about Laravel, PHP, and software development."
  images = ["img/logo.png"]


[params.social]
  twitter = "__mattallan"
  github = "matt-allan"
  email = "matt@mattallan.me"


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "about"
    url = "/about/"


# https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
    disableInlineCSS = true
  [privacy.vimeo]
    simple = true
  [privacy.youtube]
    privacyEnhanced = true