# Site settings
baseurl = "https://mattallan.me"
themesDir = "./themes"
languageCode = "en-us"
title = "Matt Allan"
theme = "brutal"
pygmentsCodeFences=true
pygmentsUseClasses=true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "about"
    url = "/about/"
