name = "Brutal"
license = "MIT"
licenselink = "https://github.com/yuloh/blog"
description = "My personal blog theme"
homepage = "http://github.com/yuloh/blog"
tags = []
features = []
min_version = "0.34"

[author]
  name = "Matt Allan"
  homepage = "mattallan.org"
